using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Specter.Generator;

[Generator]
public class MockGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var allTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Specter.GenerateMockAttribute",
                predicate: static (node, _) => node is CompilationUnitSyntax,
                transform: static (ctx, _) => GetTargets(ctx))
            .SelectMany(static (x, _) => x);

        context.RegisterSourceOutput(allTargets, static (spc, symbol) =>
        {
            if (symbol.TypeKind == TypeKind.Interface)
                Execute(spc, symbol);
            else
                ExecuteAbstractClass(spc, symbol);
        });
    }

    private static ImmutableArray<INamedTypeSymbol> GetTargets(GeneratorAttributeSyntaxContext context)
    {
        var builder = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
        foreach (var attr in context.Attributes)
        {
            if (attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is INamedTypeSymbol symbol
                && (symbol.TypeKind == TypeKind.Interface || (symbol.TypeKind == TypeKind.Class && symbol.IsAbstract)))
            {
                builder.Add(symbol);
            }
        }
        return builder.ToImmutable();
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol interfaceSymbol)
    {
        var interfaceName = interfaceSymbol.Name;
        var ns = interfaceSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : interfaceSymbol.ContainingNamespace.ToDisplayString();

        var mockClassName = GetMockClassName(interfaceName);
        var qualifiedInterface = interfaceSymbol.ToDisplayString(TypeFormat);
        var members = CollectMembers(interfaceSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Specter;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        EmitMockClass(sb, mockClassName, qualifiedInterface, members);

        var fileName = ns != null ? $"{ns}.{mockClassName}" : mockClassName;
        context.AddSource($"{fileName}.g.cs", sb.ToString());
    }

    private static string GetMockClassName(string typeName)
    {
        const int abstractPrefixLength = 8; // "Abstract".Length
        string baseName;
        if (typeName.StartsWith("Abstract") && typeName.Length > abstractPrefixLength && char.IsUpper(typeName[abstractPrefixLength]))
            baseName = typeName.Substring(abstractPrefixLength);
        else if (typeName.Length > 1 && typeName[0] == 'I' && char.IsUpper(typeName[1]))
            baseName = typeName.Substring(1);
        else
            baseName = typeName;
        return $"Mock{baseName}";
    }

    private static MemberCollection CollectMembers(INamedTypeSymbol interfaceSymbol)
    {
        var methods = new List<MethodModel>();
        var properties = new List<PropertyModel>();
        var seen = new HashSet<string>();

        void Process(INamedTypeSymbol iface)
        {
            foreach (var member in iface.GetMembers())
            {
                switch (member)
                {
                    case IMethodSymbol { MethodKind: MethodKind.Ordinary } method:
                    {
                        var key = $"m:{method.Name}({string.Join(",", method.Parameters.Select(p => p.Type.ToDisplayString(TypeFormat)))})";
                        if (seen.Add(key))
                        {
                            methods.Add(MethodModel.From(method));
                        }

                        break;
                    }
                    case IPropertySymbol prop:
                    {
                        if (seen.Add($"p:{prop.Name}"))
                        {
                            properties.Add(PropertyModel.From(prop));
                        }

                        break;
                    }
                }
            }
        }

        Process(interfaceSymbol);
        foreach (var baseInterface in interfaceSymbol.AllInterfaces)
            Process(baseInterface);

        return new MemberCollection(methods, properties);
    }

    private static void EmitVerifyInOrder(StringBuilder sb, string interceptorRef, string indent)
    {
        var i = indent;
        sb.AppendLine($"{i}public void VerifyInOrder(params ICallSpec[] steps)");
        sb.AppendLine($"{i}{{");
        sb.AppendLine($"{i}    var parsed = new (string, System.Type[]?, IMatcher[])[steps.Length];");
        sb.AppendLine($"{i}    for (int si = 0; si < steps.Length; si++)");
        sb.AppendLine($"{i}        parsed[si] = (steps[si].Method, steps[si].TypeArgs, steps[si].Matchers);");
        sb.AppendLine($"{i}    {interceptorRef}.VerifyInOrder(parsed);");
        sb.AppendLine($"{i}}}");
    }

    private static void EmitMockClass(
        StringBuilder sb, string className, string qualifiedInterface, MemberCollection members)
    {
        sb.AppendLine($"public sealed class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly MockInterceptor _interceptor;");
        sb.AppendLine($"    private readonly __Instance _inner;");
        sb.AppendLine($"    public {qualifiedInterface} Instance => _inner;");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(bool strict = false, {qualifiedInterface}? wrapping = null, System.Action<string>? onUnusedSetup = null)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        _interceptor = new(strict, wrapping, typeof({qualifiedInterface}), onUnusedSetup);");
        sb.AppendLine($"        _inner = new(_interceptor);");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    public void Reset() {{ _interceptor.Reset(); _inner.ResetState(); }}");
        sb.AppendLine($"    public void CheckUnusedSetups() => _interceptor.CheckUnusedSetups();");
        sb.AppendLine($"    public void VerifyNoOtherCalls() => _interceptor.VerifyNoOtherCalls();");
        sb.AppendLine();

        foreach (var m in members.Methods)
        {
            var typeParams = m.TypeParameterNames.Count > 0
                ? $"<{string.Join(", ", m.TypeParameterNames)}>"
                : "";
            var matcherParms = string.Join(", ", m.Parameters.Select(p => $"Matcher<{p.Type}> {p.Name}"));
            var typeArgsExpr = m.TypeParameterNames.Count > 0
                ? $"new System.Type[] {{ {string.Join(", ", m.TypeParameterNames.Select(tp => $"typeof({tp})"))} }}"
                : "null";
            var matchersExpr = m.Parameters.Count > 0
                ? $"new IMatcher[] {{ {string.Join(", ", m.Parameters.Select(p => $"{p.Name}.Inner"))} }}"
                : "Array.Empty<IMatcher>()";

            if (m.IsVoid)
            {
                sb.AppendLine($"    public VoidMethodHandle {m.Name}{typeParams}({matcherParms})");
                sb.AppendLine($"        => new(_interceptor, \"{m.Name}\", {typeArgsExpr}, {matchersExpr});");
            }
            else
            {
                sb.AppendLine($"    public MethodHandle<{m.ReturnType}> {m.Name}{typeParams}({matcherParms})");
                sb.AppendLine($"        => new(_interceptor, \"{m.Name}\", {typeArgsExpr}, {matchersExpr});");
            }
            sb.AppendLine();
        }

        foreach (var p in members.Properties)
        {
            sb.AppendLine($"    public PropertyHandle<{p.Type}> {p.Name} => new(_interceptor, \"{p.Name}\");");
            sb.AppendLine();
        }

        EmitVerifyInOrder(sb, "_interceptor", indent: "    ");
        sb.AppendLine();
        EmitInstanceClass(sb, qualifiedInterface, members, indent: "    ");
        sb.AppendLine("}");
    }

    private static void EmitInstanceClass(
        StringBuilder sb, string qualifiedInterface, MemberCollection members, string indent)
    {
        var i = indent;
        var ii = indent + "    ";

        sb.AppendLine($"{i}private sealed class __Instance : {qualifiedInterface}");
        sb.AppendLine($"{i}{{");
        sb.AppendLine($"{ii}private readonly MockInterceptor _interceptor;");

        var settableProps = members.Properties.Where(p => p.HasSetter).ToList();
        foreach (var p in settableProps)
        {
            sb.AppendLine($"{ii}private {p.Type}? _backing_{p.Name};");
            sb.AppendLine($"{ii}private bool _backing_{p.Name}_set;");
        }
        sb.AppendLine();
        sb.AppendLine($"{ii}internal __Instance(MockInterceptor interceptor) => _interceptor = interceptor;");
        sb.AppendLine();

        if (settableProps.Count > 0)
        {
            sb.AppendLine($"{ii}internal void ResetState()");
            sb.AppendLine($"{ii}{{");
            foreach (var p in settableProps)
            {
                sb.AppendLine($"{ii}    _backing_{p.Name} = default;");
                sb.AppendLine($"{ii}    _backing_{p.Name}_set = false;");
            }
            sb.AppendLine($"{ii}}}");
        }
        else
        {
            sb.AppendLine($"{ii}internal void ResetState() {{ }}");
        }
        sb.AppendLine();

        foreach (var m in members.Methods)
        {
            var typeParams = m.TypeParameterNames.Count > 0
                ? $"<{string.Join(", ", m.TypeParameterNames)}>"
                : "";
            var parms = string.Join(", ", m.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var typeArgsExpr = m.TypeParameterNames.Count > 0
                ? $"new System.Type[] {{ {string.Join(", ", m.TypeParameterNames.Select(tp => $"typeof({tp})"))} }}"
                : "null";
            var args = m.Parameters.Count > 0
                ? $"new object?[] {{ {string.Join(", ", m.Parameters.Select(p => p.Name))} }}"
                : "Array.Empty<object?>()";

            if (m.IsVoid)
            {
                sb.AppendLine($"{ii}public void {m.Name}{typeParams}({parms})");
                sb.AppendLine($"{ii}    => _interceptor.InterceptVoid(\"{m.Name}\", {typeArgsExpr}, {args});");
            }
            else
            {
                sb.AppendLine($"{ii}public {m.ReturnType} {m.Name}{typeParams}({parms})");
                sb.AppendLine($"{ii}    => _interceptor.Intercept<{m.ReturnType}>(\"{m.Name}\", {typeArgsExpr}, {args});");
            }
            sb.AppendLine();
        }

        foreach (var p in members.Properties)
        {
            sb.AppendLine($"{ii}public {p.Type} {p.Name}");
            sb.AppendLine($"{ii}{{");
            if (p.HasGetter)
            {
                if (p.HasSetter)
                    sb.AppendLine($"{ii}    get => _backing_{p.Name}_set ? _backing_{p.Name}! : _interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
                else
                    sb.AppendLine($"{ii}    get => _interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
            }
            if (p.HasSetter)
                sb.AppendLine($"{ii}    set {{ _backing_{p.Name}_set = true; _backing_{p.Name} = value; _interceptor.InterceptVoid(\"set_{p.Name}\", null, new object?[] {{ value }}); }}");
            sb.AppendLine($"{ii}}}");
            sb.AppendLine();
        }

        sb.AppendLine($"{i}}}");
    }

    private static void ExecuteAbstractClass(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        var className = classSymbol.Name;
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var mockClassName = GetMockClassName(className);
        var qualifiedClass = classSymbol.ToDisplayString(TypeFormat);
        var members = CollectAbstractClassMembers(classSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Specter;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        EmitAbstractClassMock(sb, mockClassName, qualifiedClass, members);

        var fileName = ns != null ? $"{ns}.{mockClassName}" : mockClassName;
        context.AddSource($"{fileName}.g.cs", sb.ToString());
    }

    private static MemberCollection CollectAbstractClassMembers(INamedTypeSymbol classSymbol)
    {
        var methods = new List<MethodModel>();
        var properties = new List<PropertyModel>();
        var seen = new HashSet<string>();

        INamedTypeSymbol? current = classSymbol;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in current.GetMembers())
            {
                switch (member)
                {
                    case IMethodSymbol { MethodKind: MethodKind.Ordinary } method
                        when (method.IsAbstract || method.IsVirtual)
                          && method.DeclaredAccessibility != Accessibility.Private:
                    {
                        var key = $"m:{method.Name}({string.Join(",", method.Parameters.Select(p => p.Type.ToDisplayString(TypeFormat)))})";
                        if (seen.Add(key))
                            methods.Add(MethodModel.From(method));
                        break;
                    }
                    case IPropertySymbol prop
                        when (prop.IsAbstract || prop.IsVirtual)
                          && prop.DeclaredAccessibility != Accessibility.Private:
                    {
                        if (seen.Add($"p:{prop.Name}"))
                            properties.Add(PropertyModel.From(prop));
                        break;
                    }
                }
            }
            current = current.BaseType;
        }

        return new MemberCollection(methods, properties);
    }

    private static void EmitAbstractClassMock(
        StringBuilder sb, string className, string qualifiedClass, MemberCollection members)
    {
        sb.AppendLine($"public sealed class {className} : {qualifiedClass}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly MockInterceptor _interceptor;");
        sb.AppendLine($"    public {qualifiedClass} Instance => this;");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(bool strict = false, System.Action<string>? onUnusedSetup = null) : base()");
        sb.AppendLine($"        => _interceptor = new(strict, null, typeof({qualifiedClass}), onUnusedSetup);");
        sb.AppendLine();
        sb.AppendLine("    public void Reset() => _interceptor.Reset();");
        sb.AppendLine("    public void CheckUnusedSetups() => _interceptor.CheckUnusedSetups();");
        sb.AppendLine("    public void VerifyNoOtherCalls() => _interceptor.VerifyNoOtherCalls();");
        sb.AppendLine();

        foreach (var m in members.Methods)
        {
            var typeParams = m.TypeParameterNames.Count > 0
                ? $"<{string.Join(", ", m.TypeParameterNames)}>"
                : "";
            var parms = string.Join(", ", m.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var typeArgsExpr = m.TypeParameterNames.Count > 0
                ? $"new System.Type[] {{ {string.Join(", ", m.TypeParameterNames.Select(tp => $"typeof({tp})"))} }}"
                : "null";
            var args = m.Parameters.Count > 0
                ? $"new object?[] {{ {string.Join(", ", m.Parameters.Select(p => p.Name))} }}"
                : "Array.Empty<object?>()";
            var access = m.IsProtected ? "protected" : "public";

            if (m.IsVoid)
            {
                sb.AppendLine($"    {access} override void {m.Name}{typeParams}({parms})");
                sb.AppendLine($"        => _interceptor.InterceptVoid(\"{m.Name}\", {typeArgsExpr}, {args});");
            }
            else
            {
                sb.AppendLine($"    {access} override {m.ReturnType} {m.Name}{typeParams}({parms})");
                sb.AppendLine($"        => _interceptor.Intercept<{m.ReturnType}>(\"{m.Name}\", {typeArgsExpr}, {args});");
            }
            sb.AppendLine();
        }

        var settableProps = members.Properties.Where(p => p.HasSetter).ToList();
        foreach (var p in settableProps)
        {
            sb.AppendLine($"    private {p.Type}? _backing_{p.Name};");
            sb.AppendLine($"    private bool _backing_{p.Name}_set;");
        }
        if (settableProps.Count > 0)
            sb.AppendLine();

        foreach (var p in members.Properties)
        {
            var access = p.IsProtected ? "protected" : "public";
            sb.AppendLine($"    {access} override {p.Type} {p.Name}");
            sb.AppendLine("    {");
            if (p.HasGetter)
            {
                if (p.HasSetter)
                    sb.AppendLine($"        get => _backing_{p.Name}_set ? _backing_{p.Name}! : _interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
                else
                    sb.AppendLine($"        get => _interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
            }
            if (p.HasSetter)
                sb.AppendLine($"        set {{ _backing_{p.Name}_set = true; _backing_{p.Name} = value; _interceptor.InterceptVoid(\"set_{p.Name}\", null, new object?[] {{ value }}); }}");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        EmitAbstractClassShortcuts(sb, "_interceptor", members, indent: "    ");
        EmitVerifyInOrder(sb, "_interceptor", indent: "    ");
        sb.AppendLine("}");
    }

    private static void EmitAbstractClassShortcuts(
        StringBuilder sb, string interceptorRef, MemberCollection members, string indent)
    {
        var i = indent;

        foreach (var m in members.Methods)
        {
            // Zero-parameter shortcuts can't be added: the override already occupies the same signature
            if (m.Parameters.Count == 0)
                continue;

            var typeParams = m.TypeParameterNames.Count > 0
                ? $"<{string.Join(", ", m.TypeParameterNames)}>"
                : "";
            var matcherParms = string.Join(", ", m.Parameters.Select(p => $"Matcher<{p.Type}> {p.Name}"));
            var typeArgsExpr = m.TypeParameterNames.Count > 0
                ? $"new System.Type[] {{ {string.Join(", ", m.TypeParameterNames.Select(tp => $"typeof({tp})"))} }}"
                : "null";
            var matchersExpr = $"new IMatcher[] {{ {string.Join(", ", m.Parameters.Select(p => $"{p.Name}.Inner"))} }}";

            if (m.IsVoid)
            {
                sb.AppendLine($"{i}public VoidMethodHandle {m.Name}{typeParams}({matcherParms})");
                sb.AppendLine($"{i}    => new({interceptorRef}, \"{m.Name}\", {typeArgsExpr}, {matchersExpr});");
            }
            else
            {
                sb.AppendLine($"{i}public MethodHandle<{m.ReturnType}> {m.Name}{typeParams}({matcherParms})");
                sb.AppendLine($"{i}    => new({interceptorRef}, \"{m.Name}\", {typeArgsExpr}, {matchersExpr});");
            }
            sb.AppendLine();
        }

        // Property handles use "{Name}Handle" since the mock IS the class and can't reuse the property name
        foreach (var p in members.Properties)
        {
            sb.AppendLine($"{i}public PropertyHandle<{p.Type}> {p.Name}Handle => new({interceptorRef}, \"{p.Name}\");");
            sb.AppendLine();
        }
    }

    private class MemberCollection(List<MethodModel> methods, List<PropertyModel> properties)
    {
        public List<MethodModel> Methods { get; } = methods;
        public List<PropertyModel> Properties { get; } = properties;
    }

    private class MethodModel
    {
        public string Name { get; private set; } = "";
        public string ReturnType { get; private set; } = "";
        public bool IsVoid { get; private set; }
        public bool IsProtected { get; private set; }
        public List<ParameterModel> Parameters { get; private set; } = new();
        public List<string> TypeParameterNames { get; private set; } = new();

        public static MethodModel From(IMethodSymbol s) => new()
        {
            Name = s.Name,
            IsVoid = s.ReturnsVoid,
            ReturnType = s.ReturnType.ToDisplayString(TypeFormat),
            Parameters = s.Parameters.Select(ParameterModel.From).ToList(),
            TypeParameterNames = s.TypeParameters.Select(tp => tp.Name).ToList(),
            IsProtected = s.DeclaredAccessibility == Accessibility.Protected
                       || s.DeclaredAccessibility == Accessibility.ProtectedAndInternal,
        };
    }

    private class ParameterModel
    {
        public string Name { get; private set; } = "";
        public string Type { get; private set; } = "";

        public static ParameterModel From(IParameterSymbol s) => new()
        {
            Name = s.Name,
            Type = s.Type.ToDisplayString(TypeFormat),
        };
    }

    private class PropertyModel
    {
        public string Name { get; private set; } = "";
        public string Type { get; private set; } = "";
        public bool HasGetter { get; private set; }
        public bool HasSetter { get; private set; }
        public bool IsProtected { get; private set; }

        public static PropertyModel From(IPropertySymbol s) => new()
        {
            Name = s.Name,
            Type = s.Type.ToDisplayString(TypeFormat),
            HasGetter = !s.IsWriteOnly,
            HasSetter = !s.IsReadOnly,
            IsProtected = s.DeclaredAccessibility == Accessibility.Protected
                       || s.DeclaredAccessibility == Accessibility.ProtectedAndInternal,
        };
    }
}
