using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Specter.Generator;

[Generator]
public class MockGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var allTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Specter.GenerateMockAttribute",
                predicate: static (node, _) => node is CompilationUnitSyntax,
                transform: static (ctx, _) => GetTargets(ctx))
            .SelectMany(static (x, _) => x);

        context.RegisterSourceOutput(allTargets, static (spc, symbol) =>
        {
            if (symbol.TypeKind == TypeKind.Interface)
                Execute(spc, symbol);
            else
                ExecuteAbstractClass(spc, symbol);
        });
    }

    private static ImmutableArray<INamedTypeSymbol> GetTargets(GeneratorAttributeSyntaxContext context)
    {
        var builder = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
        foreach (var attr in context.Attributes)
        {
            if (attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is INamedTypeSymbol symbol
                && (symbol.TypeKind == TypeKind.Interface || (symbol.TypeKind == TypeKind.Class && symbol.IsAbstract)))
            {
                builder.Add(symbol);
            }
        }
        return builder.ToImmutable();
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol interfaceSymbol)
    {
        var interfaceName = interfaceSymbol.Name;
        var ns = interfaceSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : interfaceSymbol.ContainingNamespace.ToDisplayString();

        var mockClassName = GetMockClassName(interfaceName);
        var setupInterfaceName = $"{interfaceName}Setup";
        var qualifiedInterface = interfaceSymbol.ToDisplayString(TypeFormat);
        var members = CollectMembers(interfaceSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Specter;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        EmitSetupInterface(sb, setupInterfaceName, members);
        sb.AppendLine();
        EmitMockClass(sb, mockClassName, setupInterfaceName, qualifiedInterface, members);

        var fileName = ns != null ? $"{ns}.{mockClassName}" : mockClassName;
        context.AddSource($"{fileName}.g.cs", sb.ToString());
    }

    private static string GetMockClassName(string typeName)
    {
        string baseName;
        if (typeName.StartsWith("Abstract") && typeName.Length > 8 && char.IsUpper(typeName[8]))
            baseName = typeName.Substring(8);
        else if (typeName.Length > 1 && typeName[0] == 'I' && char.IsUpper(typeName[1]))
            baseName = typeName.Substring(1);
        else
            baseName = typeName;
        return $"Mock{baseName}";
    }

    private static MemberCollection CollectMembers(INamedTypeSymbol interfaceSymbol)
    {
        var methods = new System.Collections.Generic.List<MethodModel>();
        var properties = new System.Collections.Generic.List<PropertyModel>();
        var seen = new System.Collections.Generic.HashSet<string>();

        void Process(INamedTypeSymbol iface)
        {
            foreach (var member in iface.GetMembers())
            {
                switch (member)
                {
                    case IMethodSymbol { MethodKind: MethodKind.Ordinary } method:
                    {
                        var key = $"m:{method.Name}({string.Join(",", method.Parameters.Select(p => p.Type.ToDisplayString(TypeFormat)))})";
                        if (seen.Add(key))
                        {
                            methods.Add(MethodModel.From(method));
                        }

                        break;
                    }
                    case IPropertySymbol prop:
                    {
                        if (seen.Add($"p:{prop.Name}"))
                        {
                            properties.Add(PropertyModel.From(prop));
                        }

                        break;
                    }
                }
            }
        }

        Process(interfaceSymbol);
        foreach (var baseInterface in interfaceSymbol.AllInterfaces)
            Process(baseInterface);

        return new MemberCollection(methods, properties);
    }

    private static void EmitSetupInterface(StringBuilder sb, string name, MemberCollection members)
    {
        sb.AppendLine($"public interface {name}");
        sb.AppendLine("{");

        foreach (var m in members.Methods)
        {
            var typeParams = m.TypeParameterNames.Count > 0
                ? $"<{string.Join(", ", m.TypeParameterNames)}>"
                : "";
            var parms = string.Join(", ", m.Parameters.Select(p => $"Matcher<{p.Type}> {p.Name}"));
            sb.AppendLine(m.IsVoid
                ? $"    void {m.Name}{typeParams}({parms});"
                : $"    {m.ReturnType} {m.Name}{typeParams}({parms});");
        }

        foreach (var p in members.Properties)
        {
            if (p.HasGetter)
            {
                sb.AppendLine($"    {p.Type} {p.Name} {{ get; }}");
            }

            if (p.HasSetter)
            {
                sb.AppendLine($"    void Set{p.Name}(Matcher<{p.Type}> value);");
            }
        }

        sb.AppendLine("}");
    }

    private static void EmitMockClass(
        StringBuilder sb, string className, string setupName, string qualifiedInterface, MemberCollection members)
    {
        sb.AppendLine($"public sealed class {className} : Mock<{qualifiedInterface}>, {qualifiedInterface}");
        sb.AppendLine("{");
        sb.AppendLine($"    public {className}(bool strict = false, {qualifiedInterface}? wrapping = null, System.Action<string>? onUnusedSetup = null) : base(strict, wrapping, onUnusedSetup) {{ }}");
        sb.AppendLine();

        foreach (var m in members.Methods)
        {
            var typeParams = m.TypeParameterNames.Count > 0
                ? $"<{string.Join(", ", m.TypeParameterNames)}>"
                : "";
            var parms = string.Join(", ", m.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var typeArgsExpr = m.TypeParameterNames.Count > 0
                ? $"new System.Type[] {{ {string.Join(", ", m.TypeParameterNames.Select(tp => $"typeof({tp})"))} }}"
                : "null";
            var args = m.Parameters.Count > 0
                ? $"new object?[] {{ {string.Join(", ", m.Parameters.Select(p => p.Name))} }}"
                : "Array.Empty<object?>()";

            if (m.IsVoid)
            {
                sb.AppendLine($"    public void {m.Name}{typeParams}({parms})");
                sb.AppendLine($"        => Interceptor.InterceptVoid(\"{m.Name}\", {typeArgsExpr}, {args});");
            }
            else
            {
                sb.AppendLine($"    public {m.ReturnType} {m.Name}{typeParams}({parms})");
                sb.AppendLine($"        => Interceptor.Intercept<{m.ReturnType}>(\"{m.Name}\", {typeArgsExpr}, {args});");
            }
            sb.AppendLine();
        }

        // Backing fields for settable properties
        var settableProps = members.Properties.Where(p => p.HasSetter).ToList();
        foreach (var p in settableProps)
        {
            sb.AppendLine($"    private {p.Type}? _backing_{p.Name};");
            sb.AppendLine($"    private bool _backing_{p.Name}_set;");
        }
        if (settableProps.Count > 0)
        {
            sb.AppendLine();
        }

        foreach (var p in members.Properties)
        {
            sb.AppendLine($"    public {p.Type} {p.Name}");
            sb.AppendLine("    {");
            if (p.HasGetter)
            {
                if (p.HasSetter)
                {
                    sb.AppendLine($"        get => _backing_{p.Name}_set ? _backing_{p.Name}! : Interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
                }
                else
                {
                    sb.AppendLine($"        get => Interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
                }
            }
            if (p.HasSetter)
            {
                sb.AppendLine($"        set {{ _backing_{p.Name}_set = true; _backing_{p.Name} = value; Interceptor.InterceptVoid(\"Set{p.Name}\", null, new object?[] {{ value }}); }}");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // OnReset override to clear backing fields
        if (settableProps.Count > 0)
        {
            sb.AppendLine("    protected override void OnReset()");
            sb.AppendLine("    {");
            foreach (var p in settableProps)
            {
                sb.AppendLine($"        _backing_{p.Name} = default;");
                sb.AppendLine($"        _backing_{p.Name}_set = false;");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine($"    public SetupBuilder<TReturn> Setup<TReturn>(Expression<Func<{setupName}, TReturn>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return new SetupBuilder<TReturn>(Interceptor.AddSetup(method, typeArgs, matchers));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public VoidSetupBuilder Setup(Expression<Action<{setupName}>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return new VoidSetupBuilder(Interceptor.AddSetup(method, typeArgs, matchers));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public SequenceSetupBuilder<TReturn> SetupSequence<TReturn>(Expression<Func<{setupName}, TReturn>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return new SequenceSetupBuilder<TReturn>(Interceptor.AddSetup(method, typeArgs, matchers));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void Verify<TReturn>(Expression<Func<{setupName}, TReturn>> expr, Specter.Times times)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        Interceptor.Verify(method, typeArgs, matchers, times);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void Verify(Expression<Action<{setupName}>> expr, Specter.Times times)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        Interceptor.Verify(method, typeArgs, matchers, times);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void VerifyInOrder(params Expression<Action<{setupName}>>[] steps)");
        sb.AppendLine("    {");
        sb.AppendLine("        Interceptor.VerifyInOrder(steps.Select(ExpressionParser.Parse).ToArray());");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public System.Collections.Generic.IReadOnlyList<Specter.CallRecord> ReceivedCalls<TReturn>(Expression<Func<{setupName}, TReturn>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return Interceptor.GetCalls(method, typeArgs, matchers).Select(c => new Specter.CallRecord(c.Args)).ToList();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public System.Collections.Generic.IReadOnlyList<Specter.CallRecord> ReceivedCalls(Expression<Action<{setupName}>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return Interceptor.GetCalls(method, typeArgs, matchers).Select(c => new Specter.CallRecord(c.Args)).ToList();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void ExecuteAbstractClass(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        var className = classSymbol.Name;
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var mockClassName = GetMockClassName(className);
        var setupInterfaceName = $"{mockClassName}Setup";
        var qualifiedClass = classSymbol.ToDisplayString(TypeFormat);
        var members = CollectAbstractClassMembers(classSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Specter;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        EmitSetupInterface(sb, setupInterfaceName, members);
        sb.AppendLine();
        EmitAbstractClassMock(sb, mockClassName, setupInterfaceName, qualifiedClass, members);

        var fileName = ns != null ? $"{ns}.{mockClassName}" : mockClassName;
        context.AddSource($"{fileName}.g.cs", sb.ToString());
    }

    private static MemberCollection CollectAbstractClassMembers(INamedTypeSymbol classSymbol)
    {
        var methods = new System.Collections.Generic.List<MethodModel>();
        var properties = new System.Collections.Generic.List<PropertyModel>();
        var seen = new System.Collections.Generic.HashSet<string>();

        INamedTypeSymbol? current = classSymbol;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in current.GetMembers())
            {
                switch (member)
                {
                    case IMethodSymbol { MethodKind: MethodKind.Ordinary } method
                        when (method.IsAbstract || method.IsVirtual)
                          && method.DeclaredAccessibility != Accessibility.Private:
                    {
                        var key = $"m:{method.Name}({string.Join(",", method.Parameters.Select(p => p.Type.ToDisplayString(TypeFormat)))})";
                        if (seen.Add(key))
                            methods.Add(MethodModel.FromWithAccessibility(method));
                        break;
                    }
                    case IPropertySymbol prop
                        when (prop.IsAbstract || prop.IsVirtual)
                          && prop.DeclaredAccessibility != Accessibility.Private:
                    {
                        if (seen.Add($"p:{prop.Name}"))
                            properties.Add(PropertyModel.FromWithAccessibility(prop));
                        break;
                    }
                }
            }
            current = current.BaseType;
        }

        return new MemberCollection(methods, properties);
    }

    private static void EmitAbstractClassMock(
        StringBuilder sb, string className, string setupName, string qualifiedClass, MemberCollection members)
    {
        sb.AppendLine($"public sealed class {className} : {qualifiedClass}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly MockInterceptor _interceptor;");
        sb.AppendLine($"    public {qualifiedClass} Instance => this;");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(bool strict = false, System.Action<string>? onUnusedSetup = null) : base()");
        sb.AppendLine($"        => _interceptor = new(strict, null, typeof({qualifiedClass}), onUnusedSetup);");
        sb.AppendLine();
        sb.AppendLine("    public void Reset() => _interceptor.Reset();");
        sb.AppendLine("    public void CheckUnusedSetups() => _interceptor.CheckUnusedSetups();");
        sb.AppendLine();

        foreach (var m in members.Methods)
        {
            var typeParams = m.TypeParameterNames.Count > 0
                ? $"<{string.Join(", ", m.TypeParameterNames)}>"
                : "";
            var parms = string.Join(", ", m.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var typeArgsExpr = m.TypeParameterNames.Count > 0
                ? $"new System.Type[] {{ {string.Join(", ", m.TypeParameterNames.Select(tp => $"typeof({tp})"))} }}"
                : "null";
            var args = m.Parameters.Count > 0
                ? $"new object?[] {{ {string.Join(", ", m.Parameters.Select(p => p.Name))} }}"
                : "Array.Empty<object?>()";
            var access = m.IsProtected ? "protected" : "public";

            if (m.IsVoid)
            {
                sb.AppendLine($"    {access} override void {m.Name}{typeParams}({parms})");
                sb.AppendLine($"        => _interceptor.InterceptVoid(\"{m.Name}\", {typeArgsExpr}, {args});");
            }
            else
            {
                sb.AppendLine($"    {access} override {m.ReturnType} {m.Name}{typeParams}({parms})");
                sb.AppendLine($"        => _interceptor.Intercept<{m.ReturnType}>(\"{m.Name}\", {typeArgsExpr}, {args});");
            }
            sb.AppendLine();
        }

        // Backing fields for settable properties
        var settableProps = members.Properties.Where(p => p.HasSetter).ToList();
        foreach (var p in settableProps)
        {
            sb.AppendLine($"    private {p.Type}? _backing_{p.Name};");
            sb.AppendLine($"    private bool _backing_{p.Name}_set;");
        }
        if (settableProps.Count > 0)
            sb.AppendLine();

        foreach (var p in members.Properties)
        {
            var access = p.IsProtected ? "protected" : "public";
            sb.AppendLine($"    {access} override {p.Type} {p.Name}");
            sb.AppendLine("    {");
            if (p.HasGetter)
            {
                if (p.HasSetter)
                    sb.AppendLine($"        get => _backing_{p.Name}_set ? _backing_{p.Name}! : _interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
                else
                    sb.AppendLine($"        get => _interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", null, Array.Empty<object?>());");
            }
            if (p.HasSetter)
                sb.AppendLine($"        set {{ _backing_{p.Name}_set = true; _backing_{p.Name} = value; _interceptor.InterceptVoid(\"Set{p.Name}\", null, new object?[] {{ value }}); }}");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Reset clears backing fields
        if (settableProps.Count > 0)
        {
            sb.AppendLine("    // Reset() already declared above; extend via partial if needed.");
            sb.AppendLine();
        }

        sb.AppendLine($"    public SetupBuilder<TReturn> Setup<TReturn>(Expression<Func<{setupName}, TReturn>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return new SetupBuilder<TReturn>(_interceptor.AddSetup(method, typeArgs, matchers));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public VoidSetupBuilder Setup(Expression<Action<{setupName}>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return new VoidSetupBuilder(_interceptor.AddSetup(method, typeArgs, matchers));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public SequenceSetupBuilder<TReturn> SetupSequence<TReturn>(Expression<Func<{setupName}, TReturn>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return new SequenceSetupBuilder<TReturn>(_interceptor.AddSetup(method, typeArgs, matchers));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void Verify<TReturn>(Expression<Func<{setupName}, TReturn>> expr, Specter.Times times)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        _interceptor.Verify(method, typeArgs, matchers, times);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void Verify(Expression<Action<{setupName}>> expr, Specter.Times times)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        _interceptor.Verify(method, typeArgs, matchers, times);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void VerifyInOrder(params Expression<Action<{setupName}>>[] steps)");
        sb.AppendLine("    {");
        sb.AppendLine("        _interceptor.VerifyInOrder(steps.Select(ExpressionParser.Parse).ToArray());");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public System.Collections.Generic.IReadOnlyList<Specter.CallRecord> ReceivedCalls<TReturn>(Expression<Func<{setupName}, TReturn>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return _interceptor.GetCalls(method, typeArgs, matchers).Select(c => new Specter.CallRecord(c.Args)).ToList();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public System.Collections.Generic.IReadOnlyList<Specter.CallRecord> ReceivedCalls(Expression<Action<{setupName}>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, typeArgs, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return _interceptor.GetCalls(method, typeArgs, matchers).Select(c => new Specter.CallRecord(c.Args)).ToList();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    // ── Data models ────────────────────────────────────────────

    private class MemberCollection(
        System.Collections.Generic.List<MethodModel> methods,
        System.Collections.Generic.List<PropertyModel> properties)
    {
        public System.Collections.Generic.List<MethodModel> Methods { get; } = methods;
        public System.Collections.Generic.List<PropertyModel> Properties { get; } = properties;
    }

    private class MethodModel
    {
        public string Name { get; private set; } = "";
        public string ReturnType { get; private set; } = "";
        public bool IsVoid { get; private set; }
        public bool IsProtected { get; private set; }
        public System.Collections.Generic.List<ParameterModel> Parameters { get; private set; } = new();
        public System.Collections.Generic.List<string> TypeParameterNames { get; private set; } = new();

        public static MethodModel From(IMethodSymbol s) => new()
        {
            Name = s.Name,
            IsVoid = s.ReturnsVoid,
            ReturnType = s.ReturnType.ToDisplayString(TypeFormat),
            Parameters = s.Parameters.Select(ParameterModel.From).ToList(),
            TypeParameterNames = s.TypeParameters.Select(tp => tp.Name).ToList(),
        };

        public static MethodModel FromWithAccessibility(IMethodSymbol s) => new()
        {
            Name = s.Name,
            IsVoid = s.ReturnsVoid,
            ReturnType = s.ReturnType.ToDisplayString(TypeFormat),
            Parameters = s.Parameters.Select(ParameterModel.From).ToList(),
            TypeParameterNames = s.TypeParameters.Select(tp => tp.Name).ToList(),
            IsProtected = s.DeclaredAccessibility == Accessibility.Protected
                       || s.DeclaredAccessibility == Accessibility.ProtectedAndInternal,
        };
    }

    private class ParameterModel
    {
        public string Name { get; private set; } = "";
        public string Type { get; private set; } = "";

        public static ParameterModel From(IParameterSymbol s) => new()
        {
            Name = s.Name,
            Type = s.Type.ToDisplayString(TypeFormat),
        };
    }

    private class PropertyModel
    {
        public string Name { get; private set; } = "";
        public string Type { get; private set; } = "";
        public bool HasGetter { get; private set; }
        public bool HasSetter { get; private set; }
        public bool IsProtected { get; private set; }

        public static PropertyModel From(IPropertySymbol s) => new()
        {
            Name = s.Name,
            Type = s.Type.ToDisplayString(TypeFormat),
            HasGetter = !s.IsWriteOnly,
            HasSetter = !s.IsReadOnly,
        };

        public static PropertyModel FromWithAccessibility(IPropertySymbol s) => new()
        {
            Name = s.Name,
            Type = s.Type.ToDisplayString(TypeFormat),
            HasGetter = !s.IsWriteOnly,
            HasSetter = !s.IsReadOnly,
            IsProtected = s.DeclaredAccessibility == Accessibility.Protected
                       || s.DeclaredAccessibility == Accessibility.ProtectedAndInternal,
        };
    }
}
