using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Specter.Generator;

[Generator]
public class MockGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interfaceTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Specter.GenerateMockAttribute",
                predicate: static (node, _) => node is CompilationUnitSyntax,
                transform: static (ctx, _) => GetTargetInterfaces(ctx))
            .SelectMany(static (x, _) => x);

        context.RegisterSourceOutput(interfaceTargets, static (spc, symbol) => Execute(spc, symbol));
    }

    private static ImmutableArray<INamedTypeSymbol> GetTargetInterfaces(GeneratorAttributeSyntaxContext context)
    {
        var builder = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
        foreach (var attr in context.Attributes)
        {
            if (attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is INamedTypeSymbol { TypeKind: TypeKind.Interface } symbol)
            {
                builder.Add(symbol);
            }
        }
        return builder.ToImmutable();
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol interfaceSymbol)
    {
        var interfaceName = interfaceSymbol.Name;
        var ns = interfaceSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : interfaceSymbol.ContainingNamespace.ToDisplayString();

        var mockClassName = GetMockClassName(interfaceName);
        var setupInterfaceName = $"{interfaceName}Setup";
        var qualifiedInterface = interfaceSymbol.ToDisplayString(TypeFormat);
        var members = CollectMembers(interfaceSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Specter;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        EmitSetupInterface(sb, setupInterfaceName, members);
        sb.AppendLine();
        EmitMockClass(sb, mockClassName, setupInterfaceName, qualifiedInterface, members);

        var fileName = ns != null ? $"{ns}.{mockClassName}" : mockClassName;
        context.AddSource($"{fileName}.g.cs", sb.ToString());
    }

    private static string GetMockClassName(string interfaceName)
    {
        var baseName = interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1])
            ? interfaceName.Substring(1)
            : interfaceName;
        return $"Mock{baseName}";
    }

    private static MemberCollection CollectMembers(INamedTypeSymbol interfaceSymbol)
    {
        var methods = new System.Collections.Generic.List<MethodModel>();
        var properties = new System.Collections.Generic.List<PropertyModel>();
        var seen = new System.Collections.Generic.HashSet<string>();

        void Process(INamedTypeSymbol iface)
        {
            foreach (var member in iface.GetMembers())
            {
                switch (member)
                {
                    case IMethodSymbol { MethodKind: MethodKind.Ordinary } method:
                    {
                        var key = $"m:{method.Name}({string.Join(",", method.Parameters.Select(p => p.Type.ToDisplayString(TypeFormat)))})";
                        if (seen.Add(key))
                            methods.Add(MethodModel.From(method));
                        break;
                    }
                    case IPropertySymbol prop:
                    {
                        if (seen.Add($"p:{prop.Name}"))
                            properties.Add(PropertyModel.From(prop));
                        break;
                    }
                }
            }
        }

        Process(interfaceSymbol);
        foreach (var baseInterface in interfaceSymbol.AllInterfaces)
            Process(baseInterface);

        return new MemberCollection(methods, properties);
    }

    private static void EmitSetupInterface(StringBuilder sb, string name, MemberCollection members)
    {
        sb.AppendLine($"public interface {name}");
        sb.AppendLine("{");

        foreach (var m in members.Methods)
        {
            var parms = string.Join(", ", m.Parameters.Select(p => $"Matcher<{p.Type}> {p.Name}"));
            sb.AppendLine(m.IsVoid
                ? $"    void {m.Name}({parms});"
                : $"    {m.ReturnType} {m.Name}({parms});");
        }

        foreach (var p in members.Properties)
        {
            if (p.HasGetter) sb.AppendLine($"    {p.Type} {p.Name} {{ get; }}");
            if (p.HasSetter) sb.AppendLine($"    void Set{p.Name}(Matcher<{p.Type}> value);");
        }

        sb.AppendLine("}");
    }

    private static void EmitMockClass(
        StringBuilder sb, string className, string setupName, string qualifiedInterface, MemberCollection members)
    {
        sb.AppendLine($"public sealed class {className} : Mock<{qualifiedInterface}>, {qualifiedInterface}");
        sb.AppendLine("{");

        foreach (var m in members.Methods)
        {
            var parms = string.Join(", ", m.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var args = m.Parameters.Count > 0
                ? $"new object?[] {{ {string.Join(", ", m.Parameters.Select(p => p.Name))} }}"
                : "Array.Empty<object?>()";

            if (m.IsVoid)
            {
                sb.AppendLine($"    public void {m.Name}({parms})");
                sb.AppendLine($"        => Interceptor.InterceptVoid(\"{m.Name}\", {args});");
            }
            else
            {
                sb.AppendLine($"    public {m.ReturnType} {m.Name}({parms})");
                sb.AppendLine($"        => Interceptor.Intercept<{m.ReturnType}>(\"{m.Name}\", {args});");
            }
            sb.AppendLine();
        }

        foreach (var p in members.Properties)
        {
            sb.AppendLine($"    public {p.Type} {p.Name}");
            sb.AppendLine("    {");
            if (p.HasGetter)
                sb.AppendLine($"        get => Interceptor.Intercept<{p.Type}>(\"get_{p.Name}\", Array.Empty<object?>());");
            if (p.HasSetter)
                sb.AppendLine($"        set => Interceptor.InterceptVoid(\"Set{p.Name}\", new object?[] {{ value }});");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine($"    public SetupBuilder<TReturn> Setup<TReturn>(Expression<Func<{setupName}, TReturn>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return new SetupBuilder<TReturn>(Interceptor.AddSetup(method, matchers));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public VoidSetupBuilder Setup(Expression<Action<{setupName}>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return new VoidSetupBuilder(Interceptor.AddSetup(method, matchers));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public SequenceSetupBuilder<TReturn> SetupSequence<TReturn>(Expression<Func<{setupName}, TReturn>> expr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        return new SequenceSetupBuilder<TReturn>(Interceptor.AddSetup(method, matchers));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void Verify<TReturn>(Expression<Func<{setupName}, TReturn>> expr, int? exactly = null, int? atLeast = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        Interceptor.Verify(method, matchers, exactly, atLeast);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public void Verify(Expression<Action<{setupName}>> expr, int? exactly = null, int? atLeast = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var (method, matchers) = ExpressionParser.Parse(expr);");
        sb.AppendLine("        Interceptor.Verify(method, matchers, exactly, atLeast);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    // ── Data models ────────────────────────────────────────────

    private class MemberCollection(
        System.Collections.Generic.List<MethodModel> methods,
        System.Collections.Generic.List<PropertyModel> properties)
    {
        public System.Collections.Generic.List<MethodModel> Methods { get; } = methods;
        public System.Collections.Generic.List<PropertyModel> Properties { get; } = properties;
    }

    private class MethodModel
    {
        public string Name { get; private set; } = "";
        public string ReturnType { get; private set; } = "";
        public bool IsVoid { get; private set; }
        public System.Collections.Generic.List<ParameterModel> Parameters { get; private set; } = new();

        public static MethodModel From(IMethodSymbol s) => new()
        {
            Name = s.Name,
            IsVoid = s.ReturnsVoid,
            ReturnType = s.ReturnType.ToDisplayString(TypeFormat),
            Parameters = s.Parameters.Select(ParameterModel.From).ToList(),
        };
    }

    private class ParameterModel
    {
        public string Name { get; private set; } = "";
        public string Type { get; private set; } = "";

        public static ParameterModel From(IParameterSymbol s) => new()
        {
            Name = s.Name,
            Type = s.Type.ToDisplayString(TypeFormat),
        };
    }

    private class PropertyModel
    {
        public string Name { get; private set; } = "";
        public string Type { get; private set; } = "";
        public bool HasGetter { get; private set; }
        public bool HasSetter { get; private set; }

        public static PropertyModel From(IPropertySymbol s) => new()
        {
            Name = s.Name,
            Type = s.Type.ToDisplayString(TypeFormat),
            HasGetter = !s.IsWriteOnly,
            HasSetter = !s.IsReadOnly,
        };
    }
}
